// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/// Generates JNI bindings for the exploratory JCA backend.
///
/// The initial binding set covers the P0 primitives from the GSoC proposal:
/// digest, HMAC, and AES-GCM. Later milestones can extend [classes] as more
/// JCA primitives are ported behind `WebCryptoImpl`.
library;

import 'dart:io';

import 'package:jnigen/jnigen.dart';

Future<void> main() async {
  final packageRoot = Platform.script.resolve('../');

  await generateJniBindings(
    Config(
      outputConfig: OutputConfig(
        dartConfig: DartCodeOutputConfig(
          path: packageRoot.resolve(
            'lib/src/impl_jni/bindings/jca_bindings.g.dart',
          ),
          structure: OutputStructure.singleFile,
        ),
      ),
      preamble:
          '// AUTO GENERATED BY JNIGEN. DO NOT EDIT!\n'
          '// Re-run tool/generate_jni_bindings.dart to regenerate.',
      summarizerOptions: SummarizerOptions(backend: SummarizerBackend.asm),
      androidSdkConfig: AndroidSdkConfig(
        addGradleDeps: true,
        androidExample: packageRoot.toFilePath(),
      ),
      classes: [
        'java.security.MessageDigest',
        'java.security.SecureRandom',
        'javax.crypto.Cipher',
        'javax.crypto.KeyGenerator',
        'javax.crypto.Mac',
        'javax.crypto.spec.GCMParameterSpec',
        'javax.crypto.spec.SecretKeySpec',
      ],
    ),
  );
}
